language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/setup-oracle-jdk6.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/build-nablarch.sh -m deploy -p ci,dev-deploy
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: OHyrSwhvfVm2hcdnZHa0TEuMiV+mU9JPjUl17b6QCURk9BYU8ITfrBWUlKPpCt2/m+xrB3UpzxuJ8helrjTgE7fg/1DLBvm0dOX8yyyXidJW5wgji+L2LLUUcjoKQX60ZZJY0rc8f//RqkCxXHeLPT2uSK1MLnF6vWhsYjAv/W4jQwaeEa6fNhBxkFjWd02PWBhb08WuudwMUZ0VPrA4b/d7777O7/YwaT+xsTPHhWCZRIkCaOnL/RfVFTiIvNNQpkFPU52GZSKlxb87kQfRD5vb8Ci/Awwqhnc76EqgWq0+M9zKO9HbhHNjB1zvSaNOV3PMgLzOqNaXe8T3YstiP6r2LJ5RjAA3DcI/wViwanmxmXm/4FKCpk8nFl29cfVbmWb3SczWXpWqHHbSfMIeRxc6BICVv8L5VpiawRUxE1eGVCqn/kw31uwh9HKVmFsyjo59Az1Mb/YZefN8ZItEEEhPqJzY5j/5HeUPG8ZQORiXNJxb+VP1XlGSZtejxPtCOxcwp21XXkrUMFw1yOf+A3NN8oz91b4gXS2TiIW4LXgQWQyTzuNqG1czy+zc7pCbMtPEklKBLCZV4SiCzFIK37/1LDVUkFyvFAYpkzWHzbpoqkrqiEOtkfHzxslQ29vsG3HfpyT1Lrxoseh9+bb2XfydB6EH+bPzDXnH+4WfHgg=
